const REQUEST_BATCH_SIZE = 10;
const BACKEND_WRITE_BATCH_SIZE = 50;
const SEASON_EPISODE_TRANSLATION_LIMIT = 10;
const BACKEND_FETCH_MIN_REFS = 3;
const GOOGLE_TRANSLATE_BATCH_SIZE = 128;
const TRAKT_DIRECT_TRANSLATION_MAX_REFS = 200;
const UNIFIED_CACHE_KEY = "dj_trakt_unified_cache";
const UNIFIED_CACHE_SCHEMA_VERSION = 2;
const UNIFIED_CACHE_MAX_BYTES = (1024 * 1024) - (8 * 1024);

const DIRECT_MEDIA_TYPE_SHOW_STATUSES = [
    "returning series",
    "ended",
    "canceled"
];

const DIRECT_MEDIA_TYPE_MOVIE_STATUSES = [
    "released",
    "post production",
    "in production"
];

const TRANSLATION_FIELDS = ["title", "overview", "tagline"];
const REQUIRED_TRANSLATION_FIELDS = ["title", "overview"];
const TRANSLATION_FALLBACK_REGIONS = ["sg", "tw", "hk"];

export {
    BACKEND_FETCH_MIN_REFS,
    BACKEND_WRITE_BATCH_SIZE,
    DIRECT_MEDIA_TYPE_MOVIE_STATUSES,
    DIRECT_MEDIA_TYPE_SHOW_STATUSES,
    GOOGLE_TRANSLATE_BATCH_SIZE,
    REQUEST_BATCH_SIZE,
    REQUIRED_TRANSLATION_FIELDS,
    SEASON_EPISODE_TRANSLATION_LIMIT,
    TRAKT_DIRECT_TRANSLATION_MAX_REFS,
    UNIFIED_CACHE_KEY,
    UNIFIED_CACHE_MAX_BYTES,
    UNIFIED_CACHE_SCHEMA_VERSION,
    TRANSLATION_FALLBACK_REGIONS,
    TRANSLATION_FIELDS
};
